apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: slush-marklogic-app
    name: slush-marklogic-node-pipeline
    template: slush-marklogic-node-pipeline
  name: slush-marklogic-node-pipeline
spec:
  runPolicy: Serial
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node() {
          stage('Build') {
            openshiftBuild(buildConfig: 'slush-marklogic-app', showBuildLogs: 'true')
          }
          stage('Deploy to Dev-Test') {
            openshiftDeploy(deploymentConfig: 'slush-marklogic-app')
          }
          stage( 'Wait for approval')
            input( 'Promote to quality assurance tests?')
          stage('Deploy QA'){
            openshiftDeploy(deploymentConfig: 'slush-marklogic-app', namespace: 'ml-qa')
          }
          stage( 'Wait for approval')
            input( 'Promote to user acceptance test?')
          stage('Deploy UAT'){
            openshiftDeploy(deploymentConfig: 'slush-marklogic-app', namespace: 'ml-uat')
          }
          stage( 'Wait for approval')
            input( 'Promote to production?')
          stage('Deploy PROD'){
            openshiftDeploy(deploymentConfig: 'slush-marklogic-app', namespace: 'ml-prod')
          }

        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
